# can 60b packet.

uint8   Object_ID       # Object ID
float64 Object_DistLong # Longitudinal (x) coordinate
float64 Object_DistLat  # Lateral (y) coordinate
float64 Object_VrelLong # Relative velocity in longitudinal direction (x)
float64 Object_VrelLat  # Relative velocity in lateral direction (y)
uint8   Object_DynProp  # Dynamic property of the object indicating if the object is moving or stationary